name: Test workflow
on:
  push:
    branches:
      - master
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python3 -m pip install pipenv
      - run: python3 -m pipenv install
      - run: python3 -m pipenv -e .
      - run: python3 -m pipenv run pytest
